<?php

namespace SoftGroup\CompaniesBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PersonsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonsRepository extends EntityRepository
{
}
