company_index:
    path:     /
    defaults: { _controller: "SoftGroupCompaniesBundle:Company:index" }
    methods:  GET

company_show:
    path:     /{id}/show
    defaults: { _controller: "SoftGroupCompaniesBundle:Company:show" }
    methods:  GET

company_new:
    path:     /new
    defaults: { _controller: "SoftGroupCompaniesBundle:Company:new" }
    methods:  [GET, POST]

company_edit:
    path:     /{id}/edit
    defaults: { _controller: "SoftGroupCompaniesBundle:Company:edit" }
    methods:  [GET, POST]

company_delete:
    path:     /{id}/delete
    defaults: { _controller: "SoftGroupCompaniesBundle:Company:delete" }
    methods:  DELETE
